# Configura»õie pentru rularea ambelor containere Docker.
services:
  monitor:
    build:
      context: .
      dockerfile: monitoring/Dockerfile
    container_name: monitor
    environment:
      - MONITORING_INTERVAL=5
    volumes:
      - system_logs:/shared
    networks:
      - monitor_net

  backup:
    build:
      context: .
      dockerfile: backup/Dockerfile
    container_name: backup
    environment:
      - INTERVAL=5
      - BACKUP_DIR=/shared
      - MAX_BACKUPS=5
    volumes:
      - system_logs:/shared
    networks:
      - monitor_net

volumes:
  system_logs:

networks:
  monitor_net: